services:
    OHMedia\BootstrapBundle\Twig\AccordionExtension:
        tags: ["twig.extension"]

    OHMedia\BootstrapBundle\Twig\FlashExtension:
        tags: ["twig.extension"]

    OHMedia\BootstrapBundle\Twig\BreadcrumbsExtension:
        autowire: true
        tags: ["twig.extension"]

    OHMedia\BootstrapBundle\Twig\NavExtension:
        arguments: ["@security.logout_url_generator"]
        tags: ["twig.extension"]

    OHMedia\BootstrapBundle\Twig\PaginationExtension:
        tags: ["twig.extension"]

    OHMedia\BootstrapBundle\Service\Paginator:
        autowire: true
